apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
        - name: app
          image: sovietspy2/blogapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: url
              valueFrom:
                secretKeyRef:
                  name: blogapp-secret
                  key: url
            - name: user
              valueFrom:
                secretKeyRef:
                  name: blogapp-secret
                  key: user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: blogapp-secret
                  key: password
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: blogapp
spec:
  selector:
    app: blogapp
  ports:
    - port: 80
      name: myport2
      targetPort: 8080
  type: LoadBalancer
