apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
spec:
  replicas: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogapp-ingress
spec:
  rules:
    - host: blogapp.tst
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogapp
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: blogapp-secret
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vdHN0LXBvc3RncmVzOjU0MzIvcG9zdGdyZXM=
