#logging:
#    level:
#        org:
#            springframework: DEBUG
server:
    port: 8080
spring:
    datasource:
        password: ${password}
        platform: postgres
        url: ${url}
        username: ${user}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                cache:
                    uri: hazelcast.xml
                    provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
                    use_query_cache: true
                    use_second_level_cache: true
                format_sql: true
                enable_lazy_load_no_trans: true
        show-sql: true



graphiql:
    mapping: /graphiql
    endpoint:
        graphql: /graphql
        subscriptions: /subscriptions
    subscriptions:
        timeout: 30
        reconnect: false
    basePath: /
    enabled: true
    pageTitle: GraphiQL
    cdn:
        enabled: false
        version: latest
    props:
        resources:

    headers:
        Authorization: "Bearer <your-token>"


#https://github.comcom/graphql-java/java-dataloader:
