--liquibase formatted sql
--changeset sovietspy2:create-blog-records

CREATE TABLE bloguser_posts
(
    id      int4 GENERATED BY DEFAULT AS IDENTITY,
    user_id int4 NOT NULL,
    posts_id int4 NOT NULL,
    CONSTRAINT bloguser_posts_pk_id UNIQUE (id),
    CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES bloguser(id),
    CONSTRAINT post_id_fk FOREIGN KEY (posts_id) REFERENCES post(id)
);

--rollback drop table bloguser_posts

