--liquibase formatted sql
--changeset sovietspy2:create-table-blog-comment-post

CREATE TABLE blog
(
    id   int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NULL,
    CONSTRAINT blog_pkey PRIMARY KEY (id)
);

-- rollback DROP TABLE blog;


CREATE TABLE comment
(
    id      int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int4 NULL,
    text    text,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT user_comment_foreign_key FOREIGN KEY (user_id) REFERENCES bloguser (id)
);

-- rollback DROP TABLE "comment";

CREATE TABLE post
(
    id      int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "text"  text         NULL,
    title   varchar(255) NULL,
    blog_id int4         NULL,
    user_id int4         NULL,
    CONSTRAINT post_pkey PRIMARY KEY (id),
    CONSTRAINT blog_foreign_key FOREIGN KEY (blog_id) REFERENCES blog (id),
    CONSTRAINT user_foreign_key FOREIGN KEY (user_id) REFERENCES bloguser(id)
);
-- rollback DROP TABLE post;


CREATE TABLE post_comments
(
    id          int4 GENERATED BY DEFAULT AS IDENTITY,
    post_id     int4   NOT NULL,
    comments_id int4   NOT NULL,
    CONSTRAINT pk_id UNIQUE (id),
    CONSTRAINT post_comment_foregin_key FOREIGN KEY (post_id) REFERENCES post (id),
    CONSTRAINT comment_post_foregin_key FOREIGN KEY (comments_id) REFERENCES comment (id)
);

-- rollback DROP TABLE post_comments;
