--liquibase formatted sql
--changeset sovietspy2:create-file-table
CREATE TABLE fileupload
(
    id      int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ctype  text         NULL,
    filename   varchar(255) NULL,
    post_id int4         NULL,
    content bytea         NULL,
    CONSTRAINT fileupload_pk PRIMARY KEY (id),
    CONSTRAINT post_id_fk_fileupload FOREIGN KEY (post_id) REFERENCES post(id)
);
-- rollback DROP TABLE fileupload;
