--liquibase formatted sql
--changeset sovietspy2:create-user-table
CREATE TABLE bloguser
(
    id serial,
    name VARCHAR (255),
    email VARCHAR(255),
    CONSTRAINT bloguser_pk PRIMARY KEY (id)
);
--rollback DROP TABLE


CREATE TABLE blog
(
    id   int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NULL,
    CONSTRAINT blog_pkey PRIMARY KEY (id)
);

--rollback DROP table blog


CREATE TABLE post
(
    id      int4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "text"  text         NULL,
    title   varchar(255) NULL,
    blog_id int4         NULL,
    user_id int4         NULL,
    CONSTRAINT post_pkey PRIMARY KEY (id),
    CONSTRAINT blog_foreign_key FOREIGN KEY (blog_id) REFERENCES blog (id),
    CONSTRAINT user_foreign_key FOREIGN KEY (user_id) REFERENCES bloguser(id)
);
-- rollback DROP TABLE post;


CREATE TABLE comment
(
    id      int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int4 NULL,
    text    text,
    post_id int4,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT user_comment_foreign_key FOREIGN KEY (user_id) REFERENCES bloguser (id),
    CONSTRAINT post_id_comment_foreign_key FOREIGN KEY (post_id) REFERENCES post(id)
);

-- rollback DROP TABLE comment;


